name: boletozz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_lucide: ^1.1.2
  intl: ^0.19.0
  file_picker: ^8.0.3
  boleto_utils: ^1.0.3
  barcode_finder: ^0.0.5
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  awesome_snackbar_content: ^0.1.3
  flutter_screenutil: ^5.9.0
  loading_animation_widget: ^1.2.1
  equatable: ^2.0.5
  flutter_speed_dial: ^7.0.0
  go_router: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  fonts:
    - family: "Poppins"
      fonts:
        - asset: lib/core/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/core/assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
        - asset: lib/core/assets/fonts/Poppins-Italic.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
